### ISSUE TITLE
panic webpki-0.21.2/src/name.rs:125:9

### ISSUE THREAD

**Issue by silence-coding** [briansmith/webpki#236]
panic in webpki-0.21.2/src/name.rs:125:9
```
impl<'a> From<DNSNameRef<'a>> for &'a str {
    fn from(DNSNameRef(d): DNSNameRef<'a>) -> Self {
        // The unwrap won't fail because DNSNameRefs are guaranteed to be ASCII
        // and ASCII is a subset of UTF-8.
        core::str::from_utf8(d).unwrap()
    }
}
```

rustls maybe in  rustls-0.17.0/src/msgs/handshake.rs:266
   `warn!("Illegal SNI hostname received {:?}", name);`
```
    fn read_hostname(r: &mut Reader) -> Option<ServerNamePayload> {
        let len = u16::read(r)? as usize;
        let name = r.take(len)?;
        let dns_name = match webpki::DNSNameRef::try_from_ascii(name) {
            Ok(dns_name) => dns_name,
            Err(_) => {
                warn!("Illegal SNI hostname received {:?}", name);
                return None;
            }
        };
        Some(ServerNamePayload::HostName(dns_name.into()))
    }
```

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 9, error_len: Some(1) }', webpki-0.21.2/src/name.rs:125:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: hiro::panic_hook::handle_panic::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:490
  12: rust_begin_unwind
             at src/libstd/panicking.rs:388
 13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:101
  14: core::option::expect_none_failed
             at src/libcore/option.rs:1272
  15: webpki::name::DNSNameRef::to_owned
  16: <webpki::name::DNSName as core::convert::From<webpki::name::DNSNameRef>>::from
  17: <rustls::msgs::handshake::ServerName as rustls::msgs::codec::Codec>::read
  18: rustls::msgs::codec::read_vec_u16
  19: <rustls::msgs::handshake::ClientExtension as rustls::msgs::codec::Codec>::read
  20: rustls::msgs::codec::read_vec_u16
  21: <rustls::msgs::handshake::ClientHelloPayload as rustls::msgs::codec::Codec>::read
  22: rustls::msgs::handshake::HandshakeMessagePayload::read_version
  23: rustls::msgs::hsjoiner::HandshakeJoiner::take_message
  24: <rustls::server::ServerSession as rustls::session::Session>::process_new_packets
  25: tokio_rustls::common::Stream<IO,S>::process_new_packets
  26: tokio_rustls::common::Stream<IO,S>::handshake
  27: <tokio_rustls::common::handshake::MidHandshake<IS> as core::future::future::Future>::poll
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  30: <futures_util::stream::futures_unordered::FuturesUnordered<Fut> as futures_core::stream::Stream>::poll_next
```

**Comment by briansmith** [comment]
Thanks for the report @silence-coding. Why did you close this?
